### ISSUE TITLE
Provide APK

### ISSUE THREAD

**Issue by varunkumarmedam** [abuanwar072/Furniture-App-UI-2-Flutter#1]
Hey nice works but it will be awesome if you can provide apk for fast reference

**Comment by chattertechno** [comment]
You can clone the repository and run on your machine. Just change some little stuff and you're good to go.

**Comment by varunkumarmedam** [comment]
yaa that's fine but providing an apk will really get the people attention quickly

**Comment by chattertechno** [comment]
Oh sure maybe @abuanwar072 he can think about it.
